name: AuraOS Final Compiler

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Build Environment
      run: |
        mkdir -p AuraOS_Build/system
        mkdir -p AuraOS_Assets
        touch AuraOS_Assets/system_tweaks.prop
        sudo apt-get update -y && sudo apt-get install -y zip

    - name: Inject AuraOS Tweaks & Compile
      run: |
        cp AuraOS_Assets/system_tweaks.prop AuraOS_Build/system/build.prop || true
        cd AuraOS_Build
        zip -r9 ../AuraOS-Stable-F127G.zip system/
        
    - name: Upload Final ROM
      uses: actions/upload-artifact@v4
      with:
        name: AuraOS-ROM-Package
        path: AuraOS-Stable-F127G.zip
