name: AuraOS Final Compiler

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Build Environment
      run: |
        echo "🚀 بدء تجميع نظام AuraOS..."
        mkdir -p AuraOS_Build/system
        sudo apt-get update && sudo apt-get install -y zip unzip

    - name: Inject AuraOS Tweaks & Assets
      run: |
        echo "⚙️ جاري دمج ملفات الأداء الخاصة بمعالج Exynos 850..."
        # هنا يقوم السيرفر بسحب الملف الذي أنشأته أنت في الخطوة السابقة
        cp AuraOS_Assets/system_tweaks.prop AuraOS_Build/system/build.prop
        
    - name: Compile and Zip System (Build ROM)
      run: |
        echo "📦 جاري ضغط النظام وبناء ملف التثبيت..."
        cd AuraOS_Build
        # ضغط الملفات لتكون جاهزة
        zip -r9 ../AuraOS-Stable-F127G.zip .
        
    - name: Upload Final ROM (Create Download Link)
      uses: actions/upload-artifact@v4
      with:
        name: AuraOS-ROM-Package
        path: AuraOS-Stable-F127G.zip
